{ inputs, ... }:
{
  imports = [
    ./recorder.nix
    ./secrets
    ./nix-ld.nix
    ./boot.nix
    ./fcitx5.nix
    ./flatpak.nix
    ./fonts.nix
    ./greetd.nix
    ./hardware.nix
    ./network.nix
    ./nfs.nix
    ./nh.nix
    ./packages.nix
    ./printing.nix
    ./security.nix
    ./services.nix
    ./starfish.nix
    ./steam.nix
    ./stylix.nix
    ./syncthing.nix
    ./system.nix
    ./thunar.nix
    ./user.nix
    ./virtualisation.nix
    ./xserver.nix
    inputs.stylix.nixosModules.stylix
    inputs.chaotic.nixosModules.default
    inputs.nur.modules.nixos.default
    inputs.agenix.nixosModules.default
  ];
}
